### ISSUE TITLE
Windows instalation error

### ISSUE THREAD

**Issue by jumc** [grupy-sanca/dojo-toolkit#42]
OSError: [WinError 193] %1 is not a valid Win32 application

pip install pgi==0.0.11.1

Collecting pgi==0.0.11.1
  Using cached pgi-0.0.11.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\setup.py", line 18, in <module>
        import pgi
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\pgi\__init__.py", line 10, in <module>
        from .importer import require_version, get_required_version
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\pgi\importer.py", line 15, in <module>
        from .clib.gir import GIRepository
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\pgi\clib\gir\__init__.py", line 8, in <module>
        from .giargument import GIArgument
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\pgi\clib\gir\giargument.py", line 9, in <module>
        from ..glib import gboolean, gint8, guint8, gint16, guint16, gint32, guint32
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\pgi\clib\glib.py", line 16, in <module>
        _glib = find_library("glib-2.0")
      File "C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\pgi\clib\_utils.py", line 99, in find_library
        _internal[name] = cdll.LoadLibrary(_so_mapping[name])
      File "C:\Users\Juliana\AppData\Local\Programs\Python\Python35\lib\ctypes\__init__.py", line 425, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\Juliana\AppData\Local\Programs\Python\Python35\lib\ctypes\__init__.py", line 347, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 is not a valid Win32 application
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Juliana\AppData\Local\Temp\pycharm-packaging\pgi\
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by jumc** [comment]
Package does not work on python 3.5
